Offchain tests
w3f/polkadot-tests pull request #148
Opened 2022-03-17 16:29 UTC by lamafab

Work-in-Progress. Some functions are left out.

2022-03-17 18:15 UTC, FlorianFranzen commented
Looks like we are running into some problem with gossamer not providing the following functions: 
- `ext_offchain_http_request_write_body_version_1`
- `ext_offchain_http_response_wait_version_1`
- `ext_offchain_http_response_headers_version_1`
- `ext_offchain_http_response_read_body_version_1`

2022-03-17 18:27 UTC, FlorianFranzen requested changes
Looks like we are running into some problem with gossamer not providing the following functions: 
- `ext_offchain_http_request_write_body_version_1`
- `ext_offchain_http_response_wait_version_1`
- `ext_offchain_http_response_headers_version_1`
- `ext_offchain_http_response_read_body_version_1`

So since they do not have any tests for them yet, I would just comment them out for now. This will be strictly necessary to merge this, as this will otherwise fail our CI every time.

Secondly, I am not sure how useful these tests are right now, apart from testing encoding. So I think in a next step, we should see what the other implementations return.

2022-03-17 18:32 UTC, FlorianFranzen commented on runtimes/hostapi/Cargo.toml
> +std = [ "sp-core/std", "parity-scale-codec" ]
What is this about?

2022-03-18 16:41 UTC, lamafab commented
I should still create some fixtures (where necessary) and integrate it with the Julia tests, on my TODO.

2022-03-21 11:50 UTC, lamafab commented on adapters/substrate/src/host_api/offchain.rs
> +}
It is, but simple enough to replicate and avoid an import. Anyway, currently it just gives us `Err(())` anyway.

2022-03-22 11:41 UTC, merged